### ISSUE TITLE
_enums_from_schema method is confusing/poorly documented

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#16]
The _enums_from_schema method (/verispy/veris.py[81:122]) was very difficult to understand, as the documentation does not describe exactly what the method does. What it looks like it does is to flatten the schema while simultaneously parsing any items that have enumerates and recording that data. This should be included in the DocString.
Maybe consider refactoring the code as well? The if/else logic is something of a mess...

**Comment by tbyers-risklens** [comment]
It could be documented better, but I didn't want to spend too much documenting what are supposed to be hidden methods.
The if-then logic is a mess because the schema is fairly complicated and there are a number of exceptions. I challenge you to do it better ;-)

**Comment by tbyers-risklens** [comment]
Maybe slightly better documentation here: https://github.com/RiskLens/verispy/commit/fe3132061a55b3532dfc8a09802735b358f64579 . Again, I don't think I can make the function much simpler because the schema itself is fairly complicated and you find the "enum" list at varied levels of the schema depending on where you are.
