### ISSUE TITLE
'No valid JSON filenames...' warning is too vague

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#17]
In the json_to_df method of the VERIS class (verispy/veris.py[378]) a warning is raised if the filenames list is empty. This list would only be empty if the directory provided contained no .json files, but the warning makes no mention of that cause. This is too vague of a warning to be useful. Should include the cause in it.

**Comment by tbyers-risklens** [comment]
Feel free to fix this to include a better warning message.

**Comment by tbyers-risklens** [comment]
https://github.com/RiskLens/verispy/pull/20

**Comment by jcherry-risklens** [comment]
??? Confused, the error message wasn't changed as a part of that pull.

**Comment by tbyers-risklens** [comment]
<img width="1004" alt="Screen Shot 2019-10-08 at 2 07 33 PM" src="https://user-images.githubusercontent.com/38048381/66433372-0e602a80-e9d5-11e9-9531-e00f506a65fa.png">
 
You changed it from a print statement to a warning, so I figured you were ok with the message. _This was your opportunity, man!_

**Comment by jcherry-risklens** [comment]
Check the line numbers, that's a different, though related message.

**Comment by tbyers-risklens** [comment]
So, the line you are talking about -- there are two ways filenames can get into that function. One, if you instantiate the object, then it loads the filenames in the `__init__` function. OR, if someone wants, they can specify the filenames themselves. So your statement "This list would only be empty if the directory provided contained no .json files, but the warning makes no mention of that cause" isn't completely true -- that's only true in the __init__ function.

The reason this is important is sometimes you might want to test or run your code on a subset of all the filenames -- OR if your files are in more than one directory, you'll combine a multiple lists. In that case, you will have to manually specify your filenames (either by slicing your original list, creating a list on your own, or concatenating two or more lists). In that case, you end up passing a list to the `json_to_df` function, with the `filenames` parameter, rather than the VERIS object finding your list of filenames and storing those in the `self.filenames` parameter.

So, you did a solid for me by changing the print statement in the `__init__` function to a `warning` (thanks!). *That* is the spot where we need to talk about the directory being empty. But if someone chooses to actually pass a list of their own filenames to `json_to_df`, then we need a different warning message, and I believe the one in there at that location is adequate. Of course, it doesn't error check if the files are actually valid files that can be parsed, but that instance would cause an error later on.

**Comment by tbyers-risklens** [comment]
I guess you could argue that the error message could be something like "Your filenames list is empty...."

**Comment by jcherry-risklens** [comment]
Aah, gotcha! Public method, ok, good point.
