### ISSUE TITLE
_enums_from_schema produces duplicate items

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#19]
It looks like every item returned from the _enums_from_schema method in veris.py returns three copies of itself within the list:
`v = VERIS('./../VCDB/data/json/validated')`
`v.load_schema()`
`schema = v._enums_from_schema(v.vschema)`
`pd.Series([schema_item['name'] for schema_item in schema]).value_counts()`
to verify.

**Comment by tbyers-risklens** [comment]
Interestingly, that's not necessarily the case.

However, I did notice that if you run your `schema = v._enums_from_schema(v.vschema)` again, it will +1 the counts for each item.

Which means we are appending each schema item to the list each time we call `_enums_from_schema` from the base state.

So, this is annoying and would be non-performant if for some reason we got into an infinite loop calling the `v._enums_from_schema` function. However, this doesn't end up causing a problem in the final data frame because when we create the data frame in `json_to_df`, we run the following:

```
        enum_list = self._enums_from_schema(self.vschema, '', [])
        self.enumerations = {item['name']: item['enumlist'] for item in enum_list if 'enumlist' in item}
        self.nonenum_vars = [item for item in enum_list if 'enumlist' not in item]
```
So duplicates will overwrite themselves. Again, not the most efficient, and certainly a mistake with my code, but also fortunately doe not appear to affect the final output.

**Comment by tbyers-risklens** [comment]
Bizarrely, if I actually specify `outlist=[]` as a parameter in the function call, we don't get this 1-up behavior:

```
schema = v._enums_from_schema(v.vschema, outlist = [])
pd.Series([schema_item['name'] for schema_item in schema]).value_counts()

action.misuse.result                     1
cost_corrective_action                   1
timeline.compromise.value                1
......
schema = v._enums_from_schema(v.vschema, outlist = [])
pd.Series([schema_item['name'] for schema_item in schema]).value_counts()

action.misuse.result                     1
cost_corrective_action                   1
timeline.compromise.value                1
```

But if I don't specify `outlist` in the parameters on the function call, it *does* do the 1-up behavior. Even though the function definition is: `_enums_from_schema(self, schema, curvarname='', outlist=[])`

```
schema = v._enums_from_schema(v.vschema)
pd.Series([schema_item['name'] for schema_item in schema]).value_counts()

action.misuse.result                      12
timeline.incident.day                     12
reference                                 12
attribute.availability.notes              12
.....


```
schema = v._enums_from_schema(v.vschema)
pd.Series([schema_item['name'] for schema_item in schema]).value_counts()

action.misuse.result                      13
timeline.incident.day                     13
reference                                 13
attribute.availability.notes              13
action.malware.vector                     13
```

Why is the value of `outlist` preserved between successive function calls even if it is instantiated as an empty list? What am I missing here?

Tempted to close this issue because it doesn't affect the actual output, but fascinated to know why this is happening...

**Comment by tbyers-risklens** [comment]
SO has the explanation: https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

**Comment by tbyers-risklens** [comment]
Per info here: http://www.omahapython.org/IdiomaticPython.html#default-parameter-values, instantiating curvarname and outlist to None fixes this issue. Thanks for noticing this and teaching me something new about Python!

Fixed in commit: https://github.com/RiskLens/verispy/commit/88c925e040cb2d49e8335d9b1ecbb117226970b9, will be available in next PR/version.
